import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import type { CalculationRecord } from '../../types';

// Create styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 30,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#0ea5e9', // Primary blue
        paddingBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#0f172a',
    },
    subtitle: {
        fontSize: 10,
        color: '#64748b',
    },
    section: {
        margin: 10,
        padding: 10,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#334155',
        backgroundColor: '#f1f5f9',
        padding: 4,
    },
    row: {
        flexDirection: 'row',
        marginBottom: 4,
        fontSize: 11,
    },
    label: {
        width: '40%',
        fontWeight: 'bold',
        color: '#475569',
    },
    value: {
        width: '60%',
        color: '#1e293b',
    },
    riskBox: {
        marginTop: 20,
        padding: 15,
        borderWidth: 1,
        borderColor: '#cbd5e1',
        borderRadius: 4,
        alignItems: 'center',
    },
    riskScore: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#dc2626', // Red by default, dynamic in logic
    },
    riskCategory: {
        fontSize: 16,
        marginTop: 5,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    disclaimer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        fontSize: 8,
        color: '#94a3b8',
        textAlign: 'center',
    }
});

interface PDFReportProps {
    record: CalculationRecord;
}

const PDFReport: React.FC<PDFReportProps> = ({ record }) => {
    const { parameters, computed, created_at, study_code, chart_name } = record;

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <View style={styles.header}>
                    <View>
                        <Text style={styles.title}>Cardiovascular Risk Report</Text>
                        <Text style={styles.subtitle}>Generated by UBIMED CVDR Calculator</Text>
                    </View>
                    <View>
                        <Text style={styles.subtitle}>{new Date(created_at).toLocaleDateString()}</Text>
                        <Text style={styles.subtitle}>ID: {record.id.slice(0, 8)}</Text>
                    </View>
                </View>

                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Patient Information</Text>
                    <View style={styles.row}>
                        <Text style={styles.label}>Study Code:</Text>
                        <Text style={styles.value}>{study_code}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Age:</Text>
                        <Text style={styles.value}>{parameters.age} years</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Sex:</Text>
                        <Text style={styles.value}>{parameters.sex}</Text>
                    </View>
                </View>

                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Clinical Parameters</Text>
                    <View style={styles.row}>
                        <Text style={styles.label}>Systolic BP:</Text>
                        <Text style={styles.value}>{parameters.sbp} mmHg</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Smoking Status:</Text>
                        <Text style={styles.value}>{parameters.smoking}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Diabetes:</Text>
                        <Text style={styles.value}>{parameters.diabetes}</Text>
                    </View>
                    {parameters.tc && (
                        <View style={styles.row}>
                            <Text style={styles.label}>Total Cholesterol:</Text>
                            <Text style={styles.value}>{parameters.tc} {parameters.tc_unit}</Text>
                        </View>
                    )}
                    <View style={styles.row}>
                        <Text style={styles.label}>Chart Used:</Text>
                        <Text style={styles.value}>{chart_name.replace(/_/g, ' ')}</Text>
                    </View>
                </View>

                <View style={styles.riskBox}>
                    <Text style={{ fontSize: 12, marginBottom: 5, color: '#64748b' }}>Estimated 10-Year CVD Risk</Text>
                    <Text style={styles.riskScore}>{computed.riskPercent}{typeof computed.riskPercent === 'number' ? '%' : ''}</Text>
                    <Text style={styles.riskCategory}>{computed.category} Risk</Text>
                </View>

                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Recommendation</Text>
                    <Text style={{ fontSize: 10, lineHeight: 1.5 }}>
                        Patients with {computed.category.toLowerCase()} risk should maximize lifestyle changes.
                        Refer to WHO/ISH guidelines for specific intervention strategies based on resource setting.
                        {computed.notes && computed.notes.length > 0 && `\n\nNotes:\n${computed.notes.join('\n')}`}
                    </Text>
                </View>

                <Text style={styles.disclaimer}>
                    This report is for clinical support only and does not replace professional medical judgment.
                    The risk estimation is based on the data provided and the selected prediction model ({chart_name}).
                </Text>
            </Page>
        </Document>
    )
};

export default PDFReport;
